"""
Generates and loads small, standalone, per-model-pack feature-computation modules.

Why this exists: a trained model pack needs to know exactly how to turn raw OHLCV
data into its selected feature matrix at evaluation/live time. Previously this was
done by pickling a closure over `selected_features` (fragile - closures don't survive
across process boundaries) or by hardcoding instrument-specific functions directly in
`Learn/features.py` (couples the generic feature library to specific model packs).

Instead, at export time the training notebook calls `write_generated_feature_module`
with the selected feature list, producing a small standalone .py file that:
  - imports the generic `add_feature_library` from `Learn.features`
  - bakes in the selected feature list as a plain Python list
  - exposes a `compute_features(df, include_mtf=True, regime_params=None)` function

The model pack stores the file's path and a sha256 hash of its contents. At eval/live
time, `load_generated_feature_module` dynamically imports the file (verifying the hash
first) and returns the `compute_features` callable - no explicit import of an
instrument-specific function name is needed anywhere in the eval/live code.
"""
import hashlib
import json
import importlib.util
from pathlib import Path


def _feature_list_hash(selected_features):
    payload = json.dumps(sorted(selected_features), sort_keys=True).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()[:10]


def write_generated_feature_module(selected_features, output_dir, dataset_slug):
    """
    Render a standalone, importable .py file that computes exactly `selected_features`
    (plus the raw OHLCV columns) by calling Learn.features.add_feature_library and
    filtering the result down to the selected columns.

    File name pattern: f"{dataset_slug}_{feature_hash}.py" under `output_dir`, so a
    different selected_features list produces a new, non-colliding file, while
    re-running with the same selection is idempotent (same hash, same filename,
    same content).

    Returns (file_path: Path, content_hash: str) where content_hash is the sha256 of
    the written file's bytes (store this in the model pack for integrity checking).
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    selected_features = list(selected_features)
    feature_hash = _feature_list_hash(selected_features)
    file_path = output_dir / f"{dataset_slug}_{feature_hash}.py"

    lines = [
        '"""',
        "Auto-generated by Learn.feature_codegen.write_generated_feature_module.",
        "Do not edit by hand - regenerate from the training notebook instead.",
        f"dataset_slug: {dataset_slug}",
        f"feature_hash: {feature_hash}",
        '"""',
        "from Learn.features import add_feature_library",
        "",
        f"SELECTED_FEATURES = {selected_features!r}",
        "",
        '_OHLCV_COLS = ["Time", "Open", "High", "Low", "Close", "Volume"]',
        "",
        "",
        "def compute_features(df, include_mtf=True, regime_params=None):",
        "    df = add_feature_library(df, include_mtf=include_mtf, regime_params=regime_params)",
        "    keep = [c for c in _OHLCV_COLS if c in df.columns]",
        "    keep += [c for c in SELECTED_FEATURES if c in df.columns and c not in keep]",
        "    return df[keep]",
        "",
    ]
    module_source = "\n".join(lines)
    file_path.write_text(module_source, encoding="utf-8")
    content_hash = hashlib.sha256(file_path.read_bytes()).hexdigest()
    return file_path, content_hash


def load_generated_feature_module(file_path, expected_hash=None):
    """
    Dynamically import a module produced by write_generated_feature_module and return
    its compute_features callable.

    If expected_hash is provided, verify it against the file's sha256 before importing
    and raise ValueError on mismatch - fail loudly rather than silently falling back to
    a different feature function.
    """
    file_path = Path(file_path)
    if not file_path.exists():
        raise FileNotFoundError(f"Generated feature module not found: {file_path}")

    if expected_hash is not None:
        actual_hash = hashlib.sha256(file_path.read_bytes()).hexdigest()
        if actual_hash != expected_hash:
            raise ValueError(
                f"Generated feature module hash mismatch for {file_path}: "
                f"expected {expected_hash}, got {actual_hash}"
            )

    module_name = f"_generated_features_{file_path.stem}"
    spec = importlib.util.spec_from_file_location(module_name, file_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.compute_features
